// Copyright 2026 Glassbox Users
// SPDX-License-Identifier: Apache-2.0

// validator.go implements stale-binding detection for generated TypeScript
// bindings.
//
// A binding directory is considered stale when any of the following is true:
//   - One or more expected output files are missing.
//   - A file's embedded ABI hash does not match the hash of the current source
//     ABI (WASM or spec file).
//   - A file has no embedded metadata (generated by an older glassbox version).
//
// The validator reads the metadata header from each generated file and compares
// the stored ABI hash against the hash computed from the current source.
package bindings

import (
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/dotandev/glassbox/internal/abi"
)

// ValidationStatus describes the freshness of a binding artifact.
type ValidationStatus string

const (
	// StatusFresh means the binding file is up-to-date with the source ABI.
	StatusFresh ValidationStatus = "fresh"
	// StatusStale means the binding file's ABI hash differs from the source.
	StatusStale ValidationStatus = "stale"
	// StatusMissing means the binding file does not exist on disk.
	StatusMissing ValidationStatus = "missing"
	// StatusNoMetadata means the file exists but has no embedded metadata
	// (generated by an older glassbox version).
	StatusNoMetadata ValidationStatus = "no-metadata"
)

// FileValidationResult holds the validation outcome for a single generated file.
type FileValidationResult struct {
	// Path is the file path relative to the binding output directory.
	Path string `json:"path"`
	// Status is the freshness status of this file.
	Status ValidationStatus `json:"status"`
	// StoredHash is the ABI hash embedded in the file (empty when missing or
	// no-metadata).
	StoredHash string `json:"storedHash,omitempty"`
	// CurrentHash is the ABI hash computed from the current source.
	CurrentHash string `json:"currentHash"`
	// GeneratedAt is the timestamp embedded in the file (zero when unavailable).
	GeneratedAt time.Time `json:"generatedAt,omitempty"`
	// Reason is a human-readable explanation of the status.
	Reason string `json:"reason,omitempty"`
}

// ValidationReport summarises the validation of an entire binding directory.
type ValidationReport struct {
	// OutputDir is the directory that was validated.
	OutputDir string `json:"outputDir"`
	// SourceABIHash is the hash of the current source ABI.
	SourceABIHash string `json:"sourceABIHash"`
	// IsStale is true when at least one file is stale, missing, or has no
	// metadata.
	IsStale bool `json:"isStale"`
	// Files contains per-file results.
	Files []FileValidationResult `json:"files"`
	// StaleCount is the number of files that are not fresh.
	StaleCount int `json:"staleCount"`
}

// ValidatorConfig holds the inputs needed to validate a binding directory.
type ValidatorConfig struct {
	// OutputDir is the directory containing the generated binding files.
	OutputDir string
	// SpecBytes is the raw ABI/spec bytes to compare against.  Mutually
	// exclusive with WasmBytes.
	SpecBytes []byte
	// SpecFormat is the format of SpecBytes.  Auto-detected when empty.
	SpecFormat abi.ImportFormat
	// WasmBytes is the raw WASM binary.  Mutually exclusive with SpecBytes.
	WasmBytes []byte
}

// generatedFileNames lists the canonical set of files produced by Generate().
var generatedFileNames = []string{
	"types.ts",
	"metadata.ts",
	"client.ts",
	"Glassbox-integration.ts",
	"index.ts",
	"package.json",
	"README.md",
}

// Validate checks whether the generated binding files in OutputDir are
// up-to-date with the provided source ABI.  It returns a ValidationReport
// describing the status of each file.
func Validate(cfg ValidatorConfig) (*ValidationReport, error) {
	currentHash, err := computeCurrentHash(cfg)
	if err != nil {
		return nil, fmt.Errorf("computing current ABI hash: %w", err)
	}

	report := &ValidationReport{
		OutputDir:     cfg.OutputDir,
		SourceABIHash: currentHash,
	}

	for _, name := range generatedFileNames {
		result := validateFile(cfg.OutputDir, name, currentHash)
		report.Files = append(report.Files, result)
		if result.Status != StatusFresh {
			report.IsStale = true
			report.StaleCount++
		}
	}

	return report, nil
}

// validateFile checks a single generated file against the expected ABI hash.
func validateFile(outputDir, name, currentHash string) FileValidationResult {
	result := FileValidationResult{
		Path:        name,
		CurrentHash: currentHash,
	}

	fullPath := filepath.Join(outputDir, name)
	content, err := os.ReadFile(fullPath)
	if err != nil {
		if os.IsNotExist(err) {
			result.Status = StatusMissing
			result.Reason = "file does not exist"
		} else {
			result.Status = StatusMissing
			result.Reason = fmt.Sprintf("cannot read file: %v", err)
		}
		return result
	}

	meta, err := ParseMetadataHeader(string(content))
	if err != nil {
		result.Status = StatusNoMetadata
		result.Reason = fmt.Sprintf("metadata parse error: %v", err)
		return result
	}
	if meta == nil {
		result.Status = StatusNoMetadata
		result.Reason = "no @glassbox-bindings-meta header found (regenerate with current glassbox)"
		return result
	}

	result.StoredHash = meta.ABIHash
	result.GeneratedAt = meta.GeneratedAt

	if meta.ABIHash == "" {
		result.Status = StatusNoMetadata
		result.Reason = "metadata header is present but abi-hash field is empty"
		return result
	}

	if meta.ABIHash != currentHash {
		result.Status = StatusStale
		result.Reason = fmt.Sprintf(
			"ABI hash mismatch: stored=%s current=%s",
			meta.ABIHash[:min8(len(meta.ABIHash))],
			currentHash[:min8(len(currentHash))],
		)
		return result
	}

	result.Status = StatusFresh
	return result
}

// computeCurrentHash derives the ABI hash from the ValidatorConfig source.
func computeCurrentHash(cfg ValidatorConfig) (string, error) {
	switch {
	case len(cfg.SpecBytes) > 0:
		return HashABIBytes(cfg.SpecBytes, cfg.SpecFormat)

	case len(cfg.WasmBytes) > 0:
		specBytes, err := abi.ExtractCustomSection(cfg.WasmBytes, "contractspecv0")
		if err != nil {
			return "", fmt.Errorf("extracting contract spec from WASM: %w", err)
		}
		if specBytes == nil {
			return "", fmt.Errorf("no contractspecv0 section found in WASM")
		}
		spec, err := abi.DecodeContractSpec(specBytes)
		if err != nil {
			return "", fmt.Errorf("decoding contract spec: %w", err)
		}
		return HashABI(spec)

	default:
		return "", fmt.Errorf("no ABI source provided: supply either WasmBytes or SpecBytes")
	}
}

// min8 returns the minimum of n and 8, used to safely truncate hashes in
// human-readable messages.
func min8(n int) int {
	if n < 8 {
		return n
	}
	return 8
}
